### ISSUE TITLE
Detection of unused rules fail if there is only self references

### ISSUE THREAD

**Issue by mingodad** [BenHanson/parsertl14#11]
While testing changes to one grammar I noticed that the detection of unused rules fail to detect unused recursive rules like:
```
unused : unused '+' unused;
```
This https://github.com/mingodad/parsertl-playground/commit/391bfb779a27b5b08e005ee4801dcc138755b7a6 seems to fix it.

**Comment by BenHanson** [comment]
Done

**Comment by mingodad** [comment]
Thank you !
