### ISSUE TITLE
Check for duplicated precedence declarations not done

### ISSUE THREAD

**Issue by mingodad** [BenHanson/parsertl14#14]
While converting this grammar https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/Parser/Parser.y to be uded in https://mingodad.github.io/parsertl-playground/playground/ I found that `parsertl` doesn't check for duplicated precedence declarations (that was present on that grammar).

This https://github.com/mingodad/parsertl-playground/commit/c5a94a611eff38caddda6f7fc7da80f3ac862223 seems to fix it.

**Comment by mingodad** [comment]
Also `parsertl` doesn't check for duplicated token declaration and this https://github.com/mingodad/parsertl-playground/commit/c9958a7e1b3f401402f795425b36d8a0632c6200 seems to somehow fix it.

**Comment by BenHanson** [comment]
It seems bison allows tokens to be re-defined.

**Comment by mingodad** [comment]
```
%token A
%token A

%left A
%left A

%%

the_a : A ;

%%
```
Output bison 3.8.2:
```
bison-nb test-dup-token.y
test-dup-token.y:2.8: warning: symbol A redeclared [-Wother]
    2 | %token A
      |        ^
test-dup-token.y:1.8: note: previous declaration
    1 | %token A
      |        ^
test-dup-token.y:5.1-5: error: %left redeclaration for A
    5 | %left A
      | ^~~~~
test-dup-token.y:4.1-5: note: previous declaration
    4 | %left A
      | ^~~~~
```

**Comment by BenHanson** [comment]
Ah, I didn't know that. Done now.
