### ISSUE TITLE
Standalone C++ parser generation

### ISSUE THREAD

**Issue by mingodad** [BenHanson/parsertl14#18]
I've just implemented (using new code and various already existing pieces from this project and related ones) a standalone `C++` parser generation.

On https://mingodad.github.io/parsertl-playground/playground/ select any grammar from `Examples` then select `Standalone C++ parser and copy to clipboard` from `Generate` then click `Parse` to get the standalone all in one `C++` parser.

It's an initial working parser that doesn't do much right now (can dump the lexer and parser tree) and any feedback is welcome.

**Comment by BenHanson** [comment]
Looking good!
