### ISSUE TITLE
Error: 'unsigned char' is not a class, struct, or union type (Compilation error with gcc 11.2.0 under MSYS2)

### ISSUE THREAD

**Issue by cwebdesign** [BenHanson/parsertl14#4]
g++ -o test main.cpp
In file included from main.cpp:4:
include/parsertl/generator.hpp: In instantiation of 'class parsertl::basic_generator<parsertl::basic_rules<char, unsigned char>, unsigned char>':
main.cpp:845:13:   required from here
include/parsertl/generator.hpp:488:15: error: 'unsigned char' is not a class, struct, or union type
  488 |         using entry = typename sm::entry;
      |               ^~~~~
main.cpp: In function 'void search_header()':
main.cpp:845:44: error: cannot convert 'gstate_machine' {aka 'parsertl::basic_state_machine<unsigned char>'} to 'unsigned char&'
  845 |                 ggenerator::build(grules_, gsm_);
      |                                            ^~~~
      |                                            |
      |                                            gstate_machine {aka parsertl::basic_state_machine<unsigned char>}
In file included from main.cpp:4:
include/parsertl/generator.hpp:52:46: note:   initializing argument 2 of 'static void parsertl::basic_generator<rules, sm, id_type>::build(rules&, sm&, std::string*) [with rules = parsertl::basic_rules<char, unsigned char>; sm = unsigned char; id_type = short unsigned int; std::string = std::__cxx11::basic_string<char>]'
   52 |         static void build(rules& rules_, sm& sm_, std::string* warnings_ = 0)
      |                                          ~~~~^~~
include/parsertl/generator.hpp: In instantiation of 'static void parsertl::basic_generator<rules, sm, id_type>::build(rules&, sm&, std::string*) [with rules = parsertl::basic_rules<char, unsigned char>; sm = unsigned char; id_type = short unsigned int; std::string = std::__cxx11::basic_string<char>]':
main.cpp:845:15:   required from here
include/parsertl/generator.hpp:67:17: error: request for member 'clear' in 'sm_', which is of non-class type 'unsigned char'
   67 |             sm_.clear();
      |             ~~~~^~~~~
In file included from L:/msys64/mingw64/include/c++/11.2.0/cassert:44,
                 from include/parsertl/../../../lexertl14/include/lexertl/lookup.hpp:9,
                 from include/parsertl/../../../lexertl14/include/lexertl/iterator.hpp:11,
                 from include/parsertl/rules.hpp:13,
                 from include/parsertl/debug.hpp:11,
                 from main.cpp:3:
include/parsertl/generator.hpp:84:45: error: request for member '_columns' in 'sm_', which is of non-class type 'unsigned char'
   84 |             assert(static_cast<id_type>(sm_._columns - 1) == sm_._columns - 1);
      |                                         ~~~~^~~~~~~~
include/parsertl/generator.hpp:84:66: error: request for member '_columns' in 'sm_', which is of non-class type 'unsigned char'
   84 |             assert(static_cast<id_type>(sm_._columns - 1) == sm_._columns - 1);
      |                                                              ~~~~^~~~~~~~
include/parsertl/generator.hpp:85:45: error: request for member '_rows' in 'sm_', which is of non-class type 'unsigned char'
   85 |             assert(static_cast<id_type>(sm_._rows - 1) == sm_._rows - 1);
      |                                         ~~~~^~~~~
include/parsertl/generator.hpp:85:63: error: request for member '_rows' in 'sm_', which is of non-class type 'unsigned char'
   85 |             assert(static_cast<id_type>(sm_._rows - 1) == sm_._rows - 1);
      |                                                           ~~~~^~~~~
In file included from main.cpp:4:
include/parsertl/generator.hpp:87:17: error: request for member '_captures' in 'sm_', which is of non-class type 'unsigned char'
   87 |             sm_._captures = rules_.captures();
      |             ~~~~^~~~~~~~~

**Comment by BenHanson** [comment]
Change the ggenerator line to:

using ggenerator = parsertl::basic_generator<grules, gstate_machine, unsigned char>;

**Comment by BenHanson** [comment]
It could be that you are simply missing -std=c++14 on the command line. I'm not sure which version of C++ gcc 11.2.0 defaults to. I have g++9.3.0, so I will attempt to upgrade.
